apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cyborg-operator
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [thoth-station.ninja]
    resources: [cyborgs]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  - apiGroups: [batch, extensions]
    resources: [jobs,cronjobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create]
